### ISSUE TITLE
[Question] Clarity on multiple versions of files in the Git repository

### ISSUE THREAD

**Issue by rahulporuri** [urbanemissions-info/pollutioncalculators#10]
Files under version control don't need to be renamed to convey version information. As such, it isn't clear to me at the moment why the following files exist

* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/Simulator.v1.xlsx
* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/Simulator.v2.xlsx
* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/Simulator.v3.xlsx
* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/Simulator.v4.xlsx

and 

* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/solver.py
* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/solver2.py

and why https://github.com/urbanemissions-info/pollutioncalculators/blob/main/waste_burning_v1.xlsx has the `_v1` suffix in the filename.

If users need to be able to access different versions based on their needs, Git/GitHub provides ways to access the versions via Tags and Releases.

**Comment by d-saikrishna** [comment]
These are not versions as per GitHub's version control. We had developed tools in multiple versions - V2 tool is superior to V1 and is used when the user has more data. I removed these tools from here and linked our website to avoid any confusion.
