### ISSUE TITLE
AQ Simulator

### ISSUE THREAD

**Issue by d-saikrishna** [urbanemissions-info/pollutioncalculators#2]
Draft: https://aqiplayer.streamlit.app/

V3 representation is pending.
V4 is pending.

**Comment by d-saikrishna** [comment]
v3

- [x] Show new zone wise conc. in the table.

**Comment by d-saikrishna** [comment]
v1 

- [x] Fix %reduction column size

**Comment by d-saikrishna** [comment]
- [x] Fix logo on top right
- [x] V2 -- the %reduction is the output (matrix output) for a given Net Reduction -- subject to max_reduction values.
- [x] V3 - One decimal is enough
- [x] V3 - Zone wise new concentration
- [x] V3 - show source apportionment table (green as well) - - warning that column sum=100. Otherwise allow the user to see the pie for each zone (dropdown)
- [x] V4 - default values for %reduction matrix should come from the solver - subject to max_reduction conditions.
- [x] Rename the app == aqsimulator

**Comment by rahulporuri** [comment]
it's not clear to me whether there are any pending tasks on this issue that external contributors can pick up

**Comment by d-saikrishna** [comment]
Closing this issue for now. I'll open one issue for each calculator that can be built.
