### ISSUE TITLE
Remove "hidden" files

### ISSUE THREAD

**Issue by rahulporuri** [urbanemissions-info/pollutioncalculators#5]
The following files seem to have been added inadvertently to the codebase

* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/.~lock.Simulator.v1.xlsx%23
* https://github.com/urbanemissions-info/pollutioncalculators/blob/main/.~lock.Simulator.v4.xlsx%23

They appear to be hidden temporary files that might have been added to the repository. If so, it will be good to remove them from the repo

**Comment by d-saikrishna** [comment]
Removed.
