### ISSUE TITLE
Use black for Python code formatting

### ISSUE THREAD

**Issue by rahulporuri** [urbanemissions-info/pollutioncalculators#7]
https://black.readthedocs.io/en/stable/index.html is a popular tool for code formatting in Python and it will be useful to format the existing Python code in the repository using the tool, in order to adhere to Python coding standards.

It will also be good to include it in the `requirements.txt` file and mention it to potential contributors.

**Comment by d-saikrishna** [comment]
Thanks for this. Reformatted all codes with Black.
